### ISSUE TITLE
ERA5-monthly source is delayed

### ISSUE THREAD

**Issue by zqianem** [byrd-polar/fluid-earth#47]
https://github.com/byrd-polar/fluid-earth/actions/runs/5815992254/job/15768435288

We are using an undocumented API to avoid extra CDS requests (see: https://github.com/ecmwf/cdsapi/issues/80#issuecomment-1668428169), but this month it did not update properly.

Hotfix is to edit `/export/data/fev2r/repository/backend/state/sources/era5monthly.js` on the prod server like so to force an update:

```diff
 {
   "last_successful_update": "2023-07-07T00:04:17.345Z",
   "date": "2023-06-01T00:00:00.000Z",
-  "last_updated": "2023-07-06",
   "normals": {
     "total_precipitation": {
       "10": "/export/data/fev2r/repository/backend/cache/738c035b-ee58-42bc-9fc4-5c5c0c0789fb"
```

@gravinamike can you take care of this?

**Comment by gravinamike** [comment]
Done! Thanks Em!

**Comment by gravinamike** [comment]
This issue has been closed.
